module.exports.relations = [
    [ { sentence: 'The angry king executed the prisoner.',
        subject: { text: 'The angry king' },
        action: { text: 'executed', lemmatized: 'execute', verb: [Object] },
        object: { text: 'the prisoner' } } ],
    [],
    [],
    [ { sentence: 'The silver flute plays a sweet melody.',
        subject: { text: 'The silver flute' },
        action: { text: 'plays', lemmatized: 'play', verb: [Object] },
        object: { text: 'a sweet melody' } } ],
    [ { sentence: 'The dramatic play entertained the common folk.',
        subject: { text: 'The dramatic play' },
        action: { text: 'entertained', lemmatized: 'entertain', verb: [Object] },
        object: { text: 'the common folk' } } ],
    [ { sentence: 'The motorbike rides into the sunset.',
        subject: { text: 'The motorbike' },
        action: { text: 'rides', lemmatized: 'ride', verb: [Object] },
        object: { text: 'into the sunset' } } ],
    [ { sentence: 'The maple tree grows tall.',
        subject: { text: 'The maple tree' },
        action: { text: 'grows', lemmatized: 'grow', verb: [Object] },
        object: { text: 'tall' } } ],
    [ { sentence: 'The root tripped the weary traveler.',
        subject: { text: 'The root' },
        action: { text: 'tripped', lemmatized: 'trip', verb: [Object] },
        object: { text: 'the weary traveler' } } ],
    [ { sentence: 'The spooky ghost scared the curious children.',
        subject: { text: 'The spooky ghost' },
        action: { text: 'scared', lemmatized: 'scare', verb: [Object] },
        object: { text: 'the curious children' } } ],
    [ { sentence: 'Kanye West sings about heartbreak and stuff.',
        subject: { text: 'Kanye West' },
        action: { text: 'sings', lemmatized: 'sing', verb: [Object] },
        object: { text: 'about heartbreak and stuff' } } ],
    [ { sentence: 'Kanye West interrupted Taylor Swift.',
        subject: { text: 'Kanye West' },
        action: { text: 'interrupted', lemmatized: 'interrupt', verb: [Object] },
        object: { text: 'Taylor Swift' } } ],
    [ { sentence: 'Kanye West brags about how awesome he is.',
        subject: { text: 'Kanye West' },
        action: { text: 'brags', lemmatized: 'brag', verb: [Object] },
        object: { text: 'about how awesome he is' } } ],
    [ { sentence: 'Santa\'s bag holds many toys.',
        subject: { text: 'Santa\'s bag' },
        action: { text: 'holds', lemmatized: 'hold', verb: [Object] },
        object: { text: 'many toys' } } ],
    [ { sentence: 'The hare raced the tortoise',
        subject: { text: 'The hare' },
        action: { text: 'raced', lemmatized: 'race', verb: [Object] },
        object: { text: 'the tortoise' } } ],
    [ { sentence: 'The black mold infects many lungs.',
        subject: { text: 'The black mold' },
        action: { text: 'infects', lemmatized: 'infect', verb: [Object] },
        object: { text: 'many lungs' } } ],
    [ { sentence: 'The professor tests his students.',
        subject: { text: 'The professor' },
        action: { text: 'tests', lemmatized: 'test', verb: [Object] },
        object: { text: 'his students' } } ],
    [ { sentence: 'The range hosted animals of all kinds.',
        subject: { text: 'animals' },
        action: { text: 'hosted', lemmatized: 'host', verb: [Object] },
        object: { text: 'The range' } } ]
];
